// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:tradly/features/cart/data/model/cart_item_model.dart';
import 'package:tradly/features/cart/data/model/cart_product_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(CartProductModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CartItemModelAdapter());
    registerAdapter(CartProductModelAdapter());
  }
}
